-- 코드를 입력하세요
SELECT SUBSTRING(SALES_DATE, 1, 10) as SALES_DATE, PRODUCT_ID, NULL as USER_ID, SALES_AMOUNT
from OFFLINE_SALE
where SUBSTRING(SALES_DATE, 1, 7) = "2022-03"
UNION ALL
SELECT SUBSTRING(SALES_DATE, 1, 10) as SALES_DATE, PRODUCT_ID,USER_ID, SALES_AMOUNT
from ONLINE_SALE
where SUBSTRING(SALES_DATE, 1, 7) = "2022-03"

order by SALES_DATE, PRODUCT_ID, USER_ID