-- 코드를 입력하세요
SELECT B.TITLE, B.BOARD_ID, R.REPLY_ID, R.WRITER_ID, R.CONTENTS, SUBSTRING(R.CREATED_DATE,1,10)
from USED_GOODS_BOARD AS B
join USED_GOODS_REPLY AS R
on B.BOARD_ID = R.BOARD_ID
where DATE_FORMAT(B.CREATED_DATE, '%y%m') = "2210"
order by R.CREATED_DATE asc, B.TITLE